---
- name: download
  shell: curl http://fuelphp.com/files/download/28 > /tmp/fuelphp.zip 
- name:  remove
  shell: rm -rf fuelphp-1.7.2
- name: unzip
  command: unzip /tmp/fuelphp.zip
- name:  remove
  command: rm -rf /var/www/fuelphp
  args:
    removes: /var/www/fuelphp
- name:  move
  command: mv fuelphp-1.7.2 /var/www/fuelphp
- name:  chown
  command: chown -R vagrant /var/www/fuelphp
- name:  chown
  command: chmod -R 777 /var/www/fuelphp
- name: setting apache config
  template: src=../files/fuelphp.conf dest=/etc/httpd/conf.d/fuelphp.conf
