---
- name: install the php-devel
  yum: name=php-devel state=installed
- name: install the php-mbstring
  yum: name=php-mbstring state=installed
- name: install the php-mysql
  yum: name=php-mysql state=installed
- name: install the php-gd
  yum: name=php-gd state=installed
- name: install the php-pear
  yum: name=php-pear state=installed
- name: install the php-bcmath
  yum: name=php-bcmath state=installed
- name: install the php-xml
  yum: name=php-xml state=installed
- name: php.ini backup
  shell: cp -a /etc/php.ini /etc/php.ini.bak
  args:
    removes: /etc/php.ini
    creates: /etc/php.ini.bak
- name: setting change date.timezone
  shell: sed -i -e "s/;date\.timezone.*/date.timezone = Asia\/Tokyo/" /etc/php.ini
